apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth #we're telling the deployment to find the pods with label app: auth
  template: #this sets the template.
    metadata:
      labels:
        app: auth #For any pod the deployment is going to create it should have the label of app: auth
    spec: #This defines the specifications/configuration of the pod we want to create
      containers:
        - name: auth
          image: flairxy/auth #auto sets to the latest version
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth' #here we just saved the value directly.
              #Howerver, if our data is security sensitive then we should use the method below which involves using
              #a security key
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
