apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets #we're telling the deployment to find the pods with label app: tickets
  template: #this sets the template.
    metadata:
      labels:
        app: tickets #For any pod the deployment is going to create it should have the label of app: tickets
    spec: #This defines the specifications/configuration of the pod we want to create
      containers:
        - name: tickets
          image: flairxy/tickets #auto sets to the latest version
          env:
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:27017/tickets' #here we just saved the value directly.
              #Howerver, if our data is security sensitive then we should use the method below which involves using
              #a security key
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
